# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  database: <%= ENV.fetch('DATABASE_DATABASE', '') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  host: <%= ENV.fetch('DATABASE_HOST', '') %>
  replica: <%= ENV.fetch('DATABASE_REPLICA_HOST', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: users_test
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', '') %>
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>

